commerce_payment.commerce_payment_gateway.plugin.square:
  type: commerce_payment_gateway_configuration
  mapping:
    app_name:
      type: string
      label: 'Application Name'
    app_secret:
      type: string
      label: 'Application Secret'
    test_app_id:
      type: string
      label: 'Sandbox Application ID'
    test_location_id:
      type: string
      label: 'Test Location ID'
    test_access_token:
      type: string
      label: 'Test Access Token'
    live_app_id:
      type: string
      label: 'Live Application ID'
    live_location_id:
      type: string
      label: 'Live Location ID'
    live_access_token:
      type: string
      label: 'Personal Access Token'
    live_access_token_expiry:
      type: string
      label: 'Token expiration'
